export const DUMMY_JOBS = [
  {
    id: 1,
    slug: "frontend-developer",
    title: "Frontend Developer",
    type: "Full-Time",
    location: "Remote",
    qualification: "Bachelor's",
    vacancies: 2,
    salary: "$40K – $60K",
    workHours: "9:00 AM – 5:00 PM",
    posted: "May 28, 2025",
    description:
      "We are seeking a talented Frontend Developer to join our growing team. You will build stunning, responsive UIs using React and Next.js and collaborate closely with designers to bring pixel-perfect experiences to life.",
    requirements:
      "The candidate must have strong knowledge of React, Next.js, TypeScript, and modern CSS frameworks. Experience with performance optimization and accessibility standards is a must.",
    requirementList: [
      "2+ years of experience with React and Next.js",
      "Strong proficiency in Tailwind CSS or similar frameworks",
      "Experience with REST APIs and state management (Zustand/Redux)",
      "Understanding of web performance and Core Web Vitals",
      "Familiarity with Git and CI/CD workflows",
      "Ability to translate Figma designs into pixel-perfect code",
    ],
    responsibilities:
      "You will be responsible for developing and maintaining client-facing web applications, collaborating with the design and backend teams, and ensuring high-quality, maintainable code.",
    responsibilityList: [
      "Build and maintain responsive web applications using Next.js",
      "Collaborate with designers to implement UI/UX designs accurately",
      "Optimize applications for maximum speed and scalability",
      "Write clean, reusable, and well-documented code",
      "Participate in code reviews and contribute to team best practices",
      "Debug and resolve frontend issues across browsers and devices",
    ],
  },
  {
    id: 2,
    slug: "seo-strategist",
    title: "SEO Strategist",
    type: "Full-Time",
    location: "New York, NY",
    qualification: "Bachelor's",
    vacancies: 1,
    salary: "$35K – $50K",
    workHours: "9:30 AM – 6:00 PM",
    posted: "May 25, 2025",
    description:
      "We are looking for a data-driven SEO Strategist to drive organic growth for our clients. You will develop and execute comprehensive SEO strategies that improve search visibility, drive traffic, and generate leads.",
    requirements:
      "The ideal candidate has deep knowledge of on-page and off-page SEO, technical SEO audits, and experience with tools like SEMrush, Ahrefs, and Google Search Console.",
    requirementList: [
      "3+ years of proven SEO experience",
      "Proficiency with SEMrush, Ahrefs, and Google Search Console",
      "Strong understanding of technical SEO and site architecture",
      "Experience with content strategy and keyword research",
      "Ability to analyze data and present actionable insights",
      "Knowledge of local and international SEO best practices",
    ],
    responsibilities:
      "You will conduct keyword research, perform technical audits, develop content strategies, and track performance metrics to continually improve organic rankings for a portfolio of clients.",
    responsibilityList: [
      "Develop and implement comprehensive SEO strategies for clients",
      "Conduct thorough keyword research and competitive analysis",
      "Perform technical SEO audits and implement recommendations",
      "Collaborate with content team to create SEO-optimized content",
      "Monitor rankings, traffic, and conversions using analytics tools",
      "Present monthly performance reports to clients and stakeholders",
    ],
  },
  {
    id: 3,
    slug: "social-media-manager",
    title: "Social Media Manager",
    type: "Part-Time",
    location: "Remote",
    qualification: "Any",
    vacancies: 1,
    salary: "$20K – $30K",
    workHours: "10:00 AM – 2:00 PM",
    posted: "May 20, 2025",
    description:
      "We are looking for a creative Social Media Manager to manage and grow brand presence across platforms including Instagram, LinkedIn, and X. You will craft compelling content and build engaged communities.",
    requirements:
      "The candidate should have a strong eye for design, excellent copywriting skills, and a deep understanding of platform algorithms and social media trends.",
    requirementList: [
      "2+ years of social media management experience",
      "Strong copywriting and content creation skills",
      "Experience with scheduling tools (Buffer, Hootsuite, Later)",
      "Understanding of platform-specific algorithms and trends",
      "Basic graphic design skills (Canva or Adobe tools)",
      "Ability to analyze insights and adjust strategy accordingly",
    ],
    responsibilities:
      "You will plan and publish content, engage with audiences, run campaigns, and provide monthly analytics reports to measure growth and impact across all social channels.",
    responsibilityList: [
      "Plan, create, and publish content across all social platforms",
      "Engage with followers and respond to comments and DMs",
      "Develop and execute social media campaigns",
      "Track performance metrics and produce monthly reports",
      "Stay current with social media trends and platform updates",
      "Collaborate with the marketing team on brand campaigns",
    ],
  },
  {
    id: 4,
    slug: "ui-ux-designer",
    title: "UI/UX Designer",
    type: "Contract",
    location: "London, UK",
    qualification: "Bachelor's",
    vacancies: 1,
    salary: "$50K – $70K",
    workHours: "9:30 AM – 6:00 PM",
    posted: "May 18, 2025",
    description:
      "We are seeking a talented and creative UI/UX Designer to join our team. The ideal candidate will design user-friendly, visually appealing digital experiences for web and mobile applications.",
    requirements:
      "The candidate must have strong skills in user interface design, visual design principles, and user experience research. A strong portfolio demonstrating design thinking and execution is essential.",
    requirementList: [
      "Proven experience as a UI/UX Designer or similar role",
      "Strong knowledge of Figma / Adobe XD / Sketch",
      "Understanding of design principles, typography & color theory",
      "Experience creating responsive web and mobile layouts",
      "Knowledge of user research, persona creation & usability testing",
      "Portfolio of previous design work",
    ],
    responsibilities:
      "The role includes conducting user research, creating wireframes and prototypes, designing modern UI layouts, and collaborating with cross-functional teams to deliver high-quality product experiences.",
    responsibilityList: [
      "Conduct user research and translate findings into design solutions",
      "Create wireframes, prototypes, and high-fidelity UI designs",
      "Design intuitive and responsive interfaces for web & mobile platforms",
      "Collaborate with product & development teams throughout the process",
      "Maintain and follow design standards and component guidelines",
      "Present design concepts and improvements to stakeholders",
    ],
  },
  {
    id: 5,
    slug: "backend-engineer",
    title: "Backend Engineer",
    type: "Full-Time",
    location: "Remote",
    qualification: "Master's",
    vacancies: 3,
    salary: "$60K – $85K",
    workHours: "9:00 AM – 5:00 PM",
    posted: "May 15, 2025",
    description:
      "We are looking for an experienced Backend Engineer to architect and maintain scalable Node.js APIs and microservices. You will work with a talented team to build robust systems that power our digital products.",
    requirements:
      "The ideal candidate has deep expertise in Node.js, Express, and MongoDB with a strong understanding of RESTful API design, authentication, and cloud deployment.",
    requirementList: [
      "4+ years of backend development experience with Node.js",
      "Strong knowledge of MongoDB, Redis, and SQL databases",
      "Experience designing and building RESTful and GraphQL APIs",
      "Familiarity with AWS, GCP, or Azure cloud services",
      "Understanding of authentication (JWT, OAuth2)",
      "Experience with Docker and containerized deployments",
    ],
    responsibilities:
      "You will design, build, and maintain backend services, collaborate with frontend teams, ensure security and scalability of APIs, and participate in architecture decisions.",
    responsibilityList: [
      "Design and develop scalable RESTful APIs and microservices",
      "Maintain and optimize database schemas and queries",
      "Ensure API security, rate limiting, and proper error handling",
      "Collaborate with frontend engineers for seamless integration",
      "Write unit and integration tests for backend services",
      "Participate in system architecture and technical planning",
    ],
  },
  {
    id: 6,
    slug: "marketing-intern",
    title: "Marketing Intern",
    type: "Internship",
    location: "Karachi, PK",
    qualification: "Any",
    vacancies: 2,
    salary: "Stipend",
    workHours: "10:00 AM – 4:00 PM",
    posted: "May 10, 2025",
    description:
      "We are looking for an enthusiastic Marketing Intern to support our marketing team. This is a great opportunity to learn hands-on digital marketing in a fast-paced agency environment.",
    requirements:
      "No prior experience required. The candidate should have a passion for digital marketing, strong communication skills, and a willingness to learn quickly.",
    requirementList: [
      "Currently pursuing or recently completed a marketing degree",
      "Strong written and verbal communication skills",
      "Basic understanding of social media platforms",
      "Eagerness to learn and take initiative",
      "Ability to work in a team environment",
      "Basic knowledge of MS Office / Google Workspace",
    ],
    responsibilities:
      "You will assist with content creation, campaign research, email marketing, and social media management while learning from experienced marketers.",
    responsibilityList: [
      "Assist in planning and executing marketing campaigns",
      "Research industry trends and competitor strategies",
      "Help create content for social media and email newsletters",
      "Support the team with administrative and coordination tasks",
      "Monitor basic analytics and prepare simple reports",
      "Attend team meetings and contribute creative ideas",
    ],
  },
];